# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
      time: '02:00'
    reviewers:
      - mburumaxwell

  - package-ecosystem: 'pip'
    directories:
      - '/identity-verification/python'
    schedule:
      interval: 'monthly'
      time: '02:00'
    reviewers:
      - sethonyango
      - mburumaxwell
    groups:
      python-packages:
        patterns: ['*']

  - package-ecosystem: 'gradle'
    directories:
      - '/identity-verification/java'
    schedule:
      interval: 'monthly'
      time: '02:00'
    reviewers:
      - sethonyango
      - mburumaxwell
    groups:
      spring-framework:
        patterns:
          - 'io.spring.*'
          - 'org.springframework.*'
