# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
  - package-ecosystem: 'pip'
    directory: '/python'
    schedule:
      interval: 'monthly'
    reviewers:
      - sethonyango
      - mburumaxwell
    groups:
      python-packages:
        patterns: ['*']
  - package-ecosystem: 'docker'
    directory: /
    schedule:
      interval: 'monthly'
    reviewers:
      - sethonyango
      - mburumaxwell
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    reviewers:
      - mburumaxwell
  - package-ecosystem: 'devcontainers'
    directory: '/'
    schedule:
      interval: 'monthly'
    reviewers:
      - mburumaxwell
