trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    exclude:
    - '**/README.md'

schedules:
- cron: "0 0 * * 0" # ensure the certs are valid
  displayName: Weekly build
  branches:
    include:
    - main

variables:
  dockerImageTag: '$(Build.BuildNumber)'
  dockerComposeFile: '**/docker-compose.yml'

steps:
- task: replacetokens@3
  displayName: 'Replace tokens in deploy folder'
  inputs:
    rootDirectory: 'deploy'
    targetFiles: |
      **/*.bicep
      **/*.parameters.json
    actionOnMissing: fail
    verbosity: detailed

- task: PublishPipelineArtifact@1
  displayName: 'Publish deploy artifact'
  inputs:
    targetPath: 'deploy'
    artifactName: 'deploy'

# Build docker images
- task: DockerCompose@0
  displayName: 'Build docker images'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: '$(dockerRegistryEndpoint)'
    dockerComposeFile: '$(dockerComposeFile)'
    action: 'Build services'
    arguments: '--parallel'

# Push docker images
- task: DockerCompose@0
  displayName: 'Push docker images'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: '$(dockerRegistryEndpoint)'
    dockerComposeFile: '$(dockerComposeFile)'
    action: 'Push services'

- task: AzureCLI@2
  displayName: 'Deploy to Infrastructure'
  inputs:
    azureSubscription: $(azureConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: >
      az deployment group create
      --resource-group $(azureResourceGroupName)
      --template-file '$(Build.SourcesDirectory)/deploy/main.bicep'
      --parameters '$(Build.SourcesDirectory)/deploy/main.parameters.json'
