FROM python:3.11-slim-buster

ENV PYTHONUNBUFFERED 1

WORKDIR /app

ADD python/requirements.txt /app/

COPY python /app/

ADD . /app/

RUN pip install -r requirements.txt

EXPOSE 8000
CMD [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
