FROM python:3.11-slim-buster

EXPOSE 8000
ENV PYTHONUNBUFFERED 1

WORKDIR /app

RUN pip install pipenv

COPY . .
RUN pipenv install --system --deploy --ignore-pipfile

CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
