version: '3.8'
services:
  identity:
    image: falu/samples/identity-verification:${DOCKER_IMAGE_TAG:-latest}
    build:
      dockerfile: Dockerfile.python
      context: .
    ports: ["8000:8000"]
