name: Cleanup

on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 */14 * *' # every 14 days

jobs:
  cleanup-updater:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        suite:
        - { name: 'falu-samples/identity-verification' }

    steps:
    - name: Delete old ${{ matrix.suite.name }} packages
      uses: actions/delete-package-versions@v5
      with:
        package-name: ${{ matrix.suite.name }}
        package-type: 'container'
        min-versions-to-keep: 10
